spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testdb;mode=mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
